# See https://docs.redoc.ly/cli/configuration/ for more information.
apiDefinitions:
  binbase: "spec/openapi.yaml"
lint:
  rules:
    api-servers: on
    camel-case-names: on
    model-description: on
    no-extra-fields: on
    operation-operationId: on
    operation-description: on
    operation-tags: on
    parameter-description: on
    path-declarations-must-exist: on
    path-keys-no-trailing-slash: on
    server-not-example: on
    servers-no-trailing-slash: on
referenceDocs:
  showConsole: true
  layout:
    scope: section
  routingStrategy: browser
  htmlTemplate: ./web/index.html
