openapi: 3.0.3
info:
  version: 1.0.0
  title: RBKmoney Organizations API
  description: >
    RBKmoney Organizations API является интерфейсом для управления различными
    аспектами вашей организации. Все изменения состояния организации, будь то
    приглашение новых сотрудников, добавление ролей уже существующим сотрудникам
    или настройка области их ответственности осуществляются с помощью вызовов
    соответствующих методов API. Любые сторонние приложения, включая ваш личный кабинет,
    являются внешними приложениями-клиентами.

    Мы предоставляем REST API поверх HTTP-протокола, схема которого описывается в
    соответствии со стандартом [OpenAPI 3][OAS3].
    Коды возврата описываются соответствующими HTTP-статусами. Платформа принимает и
    возвращает значения JSON в теле запросов и ответов.

    [OAS3]: https://swagger.io/specification/

    ## Формат содержимого

    Любой запрос к API должен выполняться в кодировке UTF-8 и с указанием
    содержимого в формате JSON.

    ```
    Content-Type: application/json; charset=utf-8
    ```

    ## Запросы

    Любой вызов методов API обязан предваряться предоставлением уникального для клиента
    платформы идентификатора запроса. Данный ID передается в соответствующем заголовке каждого
    HTTP-запроса:

    ```
        X-Request-ID: RQID-Z08G3EFE5DZ429VVO755BM19D51
    ```

    Мы требуем его, чтобы иметь возможность отследить жизненный цикл любого отдельного запроса
    в системе, когда того требуют задачи аудита или обращения в техническую поддержку.

    ### Идемпотентность

    При совершении некоторых запросов вы можете указать _ключ идемпотентности_ – уникальный набор
    символов для обеспечения идемпотентной обработки запросов.

    ```
        X-Idempotency-Key: 881D:08BA
    ```

    Даже если платформа получит множество запросов на совершение определённой операции с одним и тем
    же значением ключа идемпотентности, эта операция будет выполнена _не более чем один_ раз.
    Таким образом, в случае кратковременных проблем с сетевой доступностью вы можете отправлять запросы
    повторно и быть уверенными в том, что, например, приглашение новому сотруднику в итоге будет
    отправлено только один раз.

  termsOfService: 'https://rbk.money/'
  contact:
    name: RBKmoney Support Team
    email: support@rbk.money
    url: 'https://developer.rbk.money'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: orgs
    x-displayName: Организации
  - name: members
    x-displayName: Сотрудники
  - name: invitations
    x-displayName: Приглашения
  - name: roles
    x-displayName: Роли
  - name: error-codes
    x-displayName: Коды ошибок
    description: >
      ## Общие ошибки

      Ошибки возникающие при попытках совершения недопустимых операций, операций с невалидными объектами или несуществующими ресурсами. Имеют следующий вид:

      ```json
      {
          "code": "string",
          "message": "string"
      }
      ```

      В поле `message` содержится информация по произошедшей ошибке. Например:

      ```json
      {
          "code": "invalidRequest",
          "message": "Property 'name' is required."
      }
      ```

      ## Ошибки обработки запросов

      В процессе обработки запросов силами нашей платформы могут происходить различные непредвиденные ситуации. Об их появлении платформа сигнализирует по протоколу HTTP соответствующими [статусами][5xx], обозначающими ошибки сервера.

      |  Код    |  Описание  |
      | ------- | ---------- |
      | **500** | В процессе обработки платформой запроса возникла непредвиденная ситуация. При получении подобного кода ответа мы рекомендуем обратиться в техническую поддержку. |
      | **503** | Платформа временно недоступна и не готова обслуживать данный запрос. Запрос гарантированно не выполнен, при получении подобного кода ответа попробуйте выполнить его позднее, когда доступность платформы будет восстановлена. |
      | **504** | Платформа превысила допустимое время обработки запроса, результат запроса не определён. Попробуйте отправить запрос повторно или выяснить результат выполнения исходного запроса, если повторное исполнение запроса нежелательно. |

      [5xx]: https://tools.ietf.org/html/rfc7231#section-6.6


      Если вы получили ошибку, которой нет в данном описании, обратитесь в техническую поддержку.

servers:
  - url: 'https://{subdomain}.rbk.money/org/{version}'
    variables:
      subdomain:
        default: api
      version:
        enum:
          - v1
        default: v1
security:
  - APIKey: []
