name: Basic validation
on: [push, pull_request]

jobs:
  validate:
    name: validate spec with openapi-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm run test
